--liquibase formatted sql
--changeset Viktor_Marchuk:1

INSERT INTO cargo.country(name_country)
VALUES
    ('Albania'),
    ('Andorra'),
    ('Austria'),
    ('Belarus'),
    ('Belgium'),
    ('Bosnia and Herzegovina'),
    ('Bulgaria'),
    ('Croatia'),
    ('Cyprus'),
    ('Czech Republic'),
    ('Denmark'),
    ('Estonia'),
    ('Finland'),
    ('France'),
    ('Germany'),
    ('Greece'),
    ('Hungary'),
    ('Iceland'),
    ('Ireland'),
    ('Italy'),
    ('Kosovo'),
    ('Latvia'),
    ('Liechtenstein'),
    ('Lithuania'),
    ('Luxembourg'),
    ('Malta'),
    ('Moldova'),
    ('Monaco'),
    ('Montenegro'),
    ('Netherlands'),
    ('North Macedonia'),
    ('Norway'),
    ('Poland'),
    ('Portugal'),
    ('Romania'),
    ('San Marino'),
    ('Serbia'),
    ('Slovakia'),
    ('Slovenia'),
    ('Spain'),
    ('Sweden'),
    ('Switzerland'),
    ('Ukraine'),
    ('United Kingdom');

INSERT INTO cargo.city(name_city)
VALUES
    ('Aarhus'),
    ('Akranes'),
    ('Akureyri'),
    ('Almere'),
    ('Almería'),
    ('Amadora'),
    ('Amersfoort'),
    ('Amsterdam'),
    ('Andorra la Vella'),
    ('Antwerp'),
    ('Arnhem'),
    ('Athens'),
    ('Alytus'),
    ('Babruysk'),
    ('Baden'),
    ('Banja Luka'),
    ('Bar'),
    ('Baranavichy'),
    ('Bari'),
    ('Barcelona'),
    ('Barysaw'),
    ('Belgrade'),
    ('Berlin'),
    ('Berat'),
    ('Berane'),
    ('Bergen'),
    ('Braunshweig'),
    ('Birkirkara'),
    ('Bijelo Polje'),
    ('Bihać'),
    ('Bilbao'),
    ('Bitola'),
    ('Bologna'),
    ('Bordeaux'),
    ('Bodø'),
    ('Braunschweig'),
    ('Braşov'),
    ('Bratislava'),
    ('Bremen'),
    ('Brno'),
    ('Bruges'),
    ('Brussels'),
    ('Bucharest'),
    ('Budapest'),
    ('Burgas'),
    ('Charleroi'),
    ('Chania'),
    ('Chișinău'),
    ('Cetinje'),
    ('Celje'),
    ('Catania'),
    ('Copenhagen'),
    ('Cluj-Napoca'),
    ('Cagliari'),
    ('Cologne'),
    ('Coimbra'),
    ('Craiova'),
    ('Clervaux'),
    ('Daugavpils'),
    ('Debrecen'),
    ('Dresden'),
    ('Dubrovnik'),
    ('Dudelange'),
    ('Dublin'),
    ('Durrës'),
    ('Düsseldorf'),
    ('Edinburgh'),
    ('Eindhoven'),
    ('Encamp'),
    ('Espoo'),
    ('Esch-sur-Alzette'),
    ('Famagusta'),
    ('Florence'),
    ('Fontvieille'),
    ('Fredrikstad'),
    ('Galway'),
    ('Gamprin'),
    ('Genoa'),
    ('Graz'),
    ('Ghent'),
    ('Gjilan'),
    ('Gomel'),
    ('Gostivar'),
    ('Gdańsk'),
    ('Hafnarfjörður'),
    ('Helsinki'),
    ('Hamburg'),
    ('Herning'),
    ('Innsbruck'),
    ('Ioannina'),
    ('Jelgava'),
    ('Keflavík'),
    ('Koper'),
    ('Kosovo'),
    ('Košice'),
    ('Krems'),
    ('Krusevac'),
    ('Kuressaare'),
    ('Klaipėda'),
    ('Kyrenia'),
    ('Ljubljana'),
    ('Linz'),
    ('Lyon'),
    ('Lviv'),
    ('Luxembourg City'),
    ('Madrid'),
    ('Marseille'),
    ('Malaga'),
    ('Marijampolė'),
    ('Metz'),
    ('Milan'),
    ('Minsk'),
    ('Mostar'),
    ('Montpellier'),
    ('Nantes'),
    ('Naples'),
    ('Nikšić'),
    ('Nice'),
    ('Novi Pazar'),
    ('Novi Sad'),
    ('Olomouc'),
    ('Odense'),
    ('Ohrid'),
    ('Ostrava'),
    ('Oslo'),
    ('Palermo'),
    ('Panevėžys'),
    ('Paris'),
    ('Paphos'),
    ('Patras'),
    ('Perpignan'),
    ('Plovdiv'),
    ('Podgorica'),
    ('Porto'),
    ('Pori'),
    ('Prague'),
    ('Pristina'),
    ('Pula'),
    ('Rennes'),
    ('Reykjavík'),
    ('Riga'),
    ('Ruse'),
    ('San Marino City'),
    ('Santander'),
    ('Serravalle'),
    ('Setúbal'),
    ('Sofia'),
    ('Split'),
    ('Stockholm'),
    ('Strasbourg'),
    ('Subotica'),
    ('Tallinn'),
    ('Tartu'),
    ('Tirana'),
    ('Toulouse'),
    ('Trieste'),
    ('Turin'),
    ('Trento'),
    ('Tuzla'),
    ('Tampere'),
    ('Valencia'),
    ('Vatican City'),
    ('Vilnius'),
    ('Warsaw'),
    ('Wrocław'),
    ('Zurich');

insert into cargo.kind_of_transport(kind_transport)
values ('Tilt 82-90 m3'),
       ('Refrigerator 33 pal'),
       ('Platform'),
       ('Tilt 120 m3');

insert into cargo.contact(company_name, address, email, telephone, contact_name, password)
values ('Maersk', 'Minsk, Svobody str,9','anna@tut.by', '+375 29 8796475', 'Anna', '123');

insert into cargo.loading(loading_date, country_load_id, city_name_load_id, country_unload_id, city_name_unload_id,
                          kind_of_transport_id, name_of_load, price, contact_id)
values ('2024-03-26', 1, 1, 2, 4, 1, 'plastic on pallets', 1250, 1),
       ('2024-03-30', 4, 7, 3, 12, 2, 'Meat ,temp -18', 2540, 1),
       ('2024-04-01', 2, 5, 3, 12, 4, 'Izolation on pallets', 1800, 1);



